
spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/pet-project?currentSchema=java
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  liquibase:
    changeLog: "classpath:db/changelog/changelog-master.xml"
    enabled: true
